export { default as LoginPage } from './Login'
export { default as RegisterPage } from './Register'
export { default as LandingPage } from './LandingPage'
export { default as ProfilePage } from './ProfilePage'
export { default as BikeDetailPage } from './BikeDetailPage'
export { default as BikeFormPage } from './BikeFormPage'
